version: "2"
linters:
  enable:
    - dogsled
    - errcheck
    - gocritic
    - govet
    - gocyclo
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
formatters:
  enable:
    - gofmt
    - goimports
