FROM golang:1.21 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/dbbrowser/ ./
COPY pkg ./pkg
RUN CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o /dbbrowser

FROM alpine:3
WORKDIR /
RUN apk add --no-cache ca-certificates
COPY --from=builder /dbbrowser /dbbrowser
EXPOSE 8080
CMD ["/dbbrowser", "-use_cloudsql", "-use_iam_auth"]
