FROM golang:1.21 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/gopogh-server/main.go ./
COPY pkg ./pkg
RUN CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o /gopogh-server

FROM alpine:3
WORKDIR /
RUN apk add --no-cache ca-certificates
COPY --from=builder /gopogh-server /gopogh-server
EXPOSE 8080
CMD ["/gopogh-server", "-use_cloudsql", "-use_iam_auth"]
