FROM golang:1.24 AS builder
WORKDIR /app
COPY Makefile ./
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/gopogh-server/main.go ./cmd/gopogh-server/main.go
COPY pkg ./pkg
RUN make server

FROM alpine:3
LABEL "org.opencontainers.image.source"="https://github.com/medyagh/gopogh"
WORKDIR /
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/out/gopogh-server /gopogh-server
EXPOSE 8080
CMD ["/gopogh-server", "-use_cloudsql", "-use_iam_auth"]
